---
# Playbook for  Hadoop master servers

- name: Install the namenode and jobtracker packages
  apt: name={{item}} state=latest
  with_items:
   - hadoop-hdfs-namenode
   - hadoop-0.20-mapreduce-jobtracker
   - hadoop-doc

- name: Create the data directory for the namenode metadata
  file: path={{ item }} owner=hdfs group=hdfs state=directory
  with_items: hadoop.dfs_namenode_name_dir

- name: Copy the hadoop configuration files for no ha
  template: src=roles/hadoop_common/templates/hadoop_conf/{{item}}.j2 dest=/etc/hadoop/conf/{{item}} mode=644
  with_items: 
   - core-site.xml
   - hadoop-metrics.properties
   - hadoop-metrics2.properties
   - hdfs-site.xml
   - log4j.properties
   - mapred-site.xml
   - hadoop-env.sh
   - slaves
  notify: restart hadoop master services

- name: Format the namenode
  shell: creates=/usr/lib/hadoop/namenode.formatted su - hdfs -c "hadoop namenode -format" && touch /usr/lib/hadoop/namenode.formatted

- name: start hadoop namenode services
  service: name=hadoop-hdfs-namenode state=started

- name: Give permissions for mapred users
  shell: creates=/usr/lib/hadoop/namenode.initialized su - hdfs -c "hdfs dfs -chown hdfs:hadoop /"; su - hdfs -c "hdfs dfs -chmod 0775 /" && touch /usr/lib/hadoop/namenode.initialized
